paginate:  5
permalink: /posts/:title/
url:       http://zofe.com.br
auto:      true
server:    true
markdown:  Kramdown
excerpt_separator: ""

title: "Zone Of Front-Enders - ZOFE"
exclude: [episodios]
