paginate:  5
permalink: /posts/:title/
url:       http://zofe.com.br
markdown:  Kramdown
excerpt_separator: ""

title: "Zone Of Front-Enders - ZOFE"
exclude: [
  'episodios',
  'README.md',
  'package.json',
  'Gruntfile.js',
  'node_modules',
  'Gemfile*',
  'assets/sass'
]
cover-image: "../assets/img/covers/cover-image.jpg"
